### ISSUE TITLE
Recognize 3DTouch even on mobile emulator ( chrome ) 

### ISSUE THREAD

**Issue by LukyVj** [freinbichler/3d-touch#1]
Hi, 

wonderful project, idea & realisation. 
Because I don't have any iPhone6S I cannot really try it, but I tried with the phone emulator of google chrome.

And it seems that iphone6 (emulated) can force touch if you keep the button pressed. 
Same with iPad (emulated) and well, any emulated devices.

**Comment by rocketinventor** [comment]
@LukyVj Great tip, thanks.

**Comment by Haroenv** [comment]
Or on a MBP with force touch it works too.
