### ISSUE TITLE
apple-mobile-web-app-capable on homescreen

### ISSUE THREAD

**Issue by hsleewis** [freinbichler/3d-touch#5]
3D touch doesn't work when the website is pushed on the homescreen when apple-mobile-web-app-capable is enabled. Any clue how to get that to work?

**Comment by freinbichler** [comment]
You mean quick actions on the app icon when you add it to homescreen? I'm pretty sure that's not possible.

**Comment by hsleewis** [comment]
No,that's not what I meant.

 I've built it in a small webapp, if I run that webapp in safari it works perfectly.
But if you add the header:
`<meta name="apple-mobile-web-app-capable" content="yes">`
and add the website to your homescreen it runs full screen, but than 3D Touch doesn't work.

You can see it for yourself if you add the header to your demo and put the site on your homescreen. :)

**Comment by freinbichler** [comment]
The force value might only work in full Safari. If it does not work I don't think that there is a workaround.
