### ISSUE TITLE
ios10 (thank you)

### ISSUE THREAD

**Issue by spencercap** [freinbichler/3d-touch#9]
hey, 
thanks for the quick iOS 10 update. 
re-implementing it into a project of mine. 
sc

**Comment by freinbichler** [comment]
no problem, have fun!

**Comment by spencercap** [comment]
looks like Apple took away the force touch attribute from the abbreviated "Safari" that opens when a website is saved to the home screen. was working on iOS9... 

made a little coloring app: 
[http://sites.bxmc.poly.edu/~spencercappiello/color-draw04/]

**Comment by freinbichler** [comment]
The old timeout-based method on iOS 9 also did not work when added to homescreen. See issue #5 for reference.
